fields:
  - name: apps
    type: text
    caption: Apps
    tooltip: List of apps to enable, make sure to use double quotes and square brackets
    default: '["dcim.device", "virtualization.virtualmachine"]'
    required: true

  - name: display_default
    type: list
    caption: Display Default
    tooltip: Where to display the secret on the detail page of the defined apps
    values:
      - value: left_page
        caption: Left Page
      - value: right_page
        caption: Right Page
      - value: full_width_page
        caption: Full Width Page
    default: left_page

  - name: display_setting
    type: text
    caption: Display Setting
    tooltip: Set display setting for concrete model
    default: '{}'

  - name: enable_contacts
    type: checkbox
    caption: Enable Contacts
    tooltip: Enable Contacts
    default: false

  - name: public_key_size
    type: list
    caption: Public Key Size
    tooltip: Size of the public key
    values:
      - value: 2048
        caption: 2048
      - value: 4096
        caption: 4096
      - value: 8192
        caption: 8192
    default: 2048

  - name: restartContainer
    type: checkbox
    caption: Restart NetBox container
    tooltip: Restart NetBox container after install/uninstall
    default: true
    required: false
