default: v1.9.0
versions:
- caption: v1.9.0
  value: v1.9.0
- caption: v1.8.5
  value: v1.8.5
- caption: v1.8.4
  value: v1.8.4
- caption: v1.8.3
  value: v1.8.3
- caption: v1.8.2
  value: v1.8.2
- caption: v1.8.1
  value: v1.8.1
- caption: v1.8.0
  value: v1.8.0
- caption: v1.7.6
  value: v1.7.6
- caption: v1.7.5
  value: v1.7.5
- caption: v1.7.4
  value: v1.7.4
- caption: v1.7.3
  value: v1.7.3
- caption: v1.7.2
  value: v1.7.2
- caption: v1.7.1
  value: v1.7.1
- caption: v1.7.0
  value: v1.7.0
- caption: v1.6.0
  value: v1.6.0
- caption: v1.5.0
  value: v1.5.0
- caption: v1.4.0
  value: v1.4.0
