fields:
  - name: oauth_key
    caption: Oauth2 Key
    type: string
    required: true

  - name: oauth_secret
    caption: Oauth2 Secret
    type: string
    required: true

  - name: groups_isstaff
    caption: Groups for Staff
    type: string
    required: false
    tooltip: Comma-separated list of AzureAD groups that should be considered staff.

  - name: groups_issuperuser
    caption: Groups for Superusers
    type: string
    required: false
    tooltip: Comma-separated list of AzureAD groups that should be considered superusers.

  - name: group_mapping
    caption: Group Mapping
    type: text
    required: true
    tooltip: |-
      Dictionary mapping AzureAD groups to NetBox groups. The key is the AzureAD group name, and the value is the NetBox group name.
      Example: {"AzureAD Group Name": "NetBox Group Name"}

  - name: group_permission_mapping
    caption: Group Permission Mapping
    type: text
    required: true
    tooltip: |-
      Dictionary mapping AzureAD groups to NetBox permissions. The key is the AzureAD group name, and the value is an object of the form {"app.model": ["add", "change", "delete", "view"]}.
      Example: {"AzureAD Group Name": {"dcim.site": ["add", "change", "delete", "view"]}}
