fields:
  - name: backupRegion
    type: regionlist
    caption: Backup Region
    tooltip: Choose a region for database backups, preferably in a different availability zone
    required: true
    disableInactive: true
    hidden: false

  - name: backupType
    type: list
    caption: Backup Storage Type
    tooltip: Storage type for database backups
    values:
      - value: 1
        caption: Standalone Storage
      - value: 2
        caption: Cluster Storage
    default: 1
    showIf:
      2:
        - name: backupNodesCount
          type: spinner
          caption: Nodes Count
          tooltip: Number of nodes in the backup cluster
          default: 3
          min: 3
          max: 7

  - name: backupDiskLimit
    type: spinner
    caption: Backup Disk Size
    tooltip: Size of the backup disk in GB
    default: 100
    required: true
    editable: true
    min: 5

  - name: backupSchedule
    type: list
    caption: Backup Schedule
    tooltip: Schedule for database backups
    values:
      - value: 0 * * * *
        caption: "Hourly (at minute 0)"
      - value: 0 0 * * *
        caption: "Daily (at 00:00)"
      - value: 0 0 * * 0
        caption: "Weekly (at 00:00 on Sunday)"
      - value: 0 0 1 * *
        caption: "Monthly (at 00:00 on day 1)"
    default: 0 0 * * *

  - name: backupCount
    type: spinner
    caption: Number of backups
    tooltip: "The number of newest backups to be kept during rotation."
    min: 1
    max: 30
    default: 5

  - name: dbPassword
    type: string
    caption: Database Password
    tooltip: Check your email for the "webadmin" password
    required: true
    inputType: password
