fields:
  - name: version
    type: list
    caption: Version
    tooltip: Version of plugin to install
    values:
      - value: v0.0.5
        caption: v0.0.5
      - value: v0.1.0
        caption: v0.1.0
    default: v0.1.0

  - name: repoOwner
    type: string
    caption: Repository Owner
    required: false
    default: netbox-community

  - name: repo
    type: string
    caption: Repository
    required: false
    default: devicetype-library

  - name: branch
    type: string
    caption: Branch
    required: false
    default: master

  - name: githubToken
    type: string
    caption: GitHub Token
    required: false

  - name: restartContainer
    type: checkbox
    caption: Restart NetBox container
    tooltip: Restart NetBox container after install/uninstall
    default: true
    required: false
