fields:
  - name: version
    type: list
    caption: NetBox Version
    tooltip: Version of NetBox to install
    values:
      - value: v3.3
        caption: v3.3
      - value: v3.4-2.5.3
        caption: v3.4
    default: v3.4-2.5.3

  - type: compositefield
    caption: Admin Username
    defaultMargins: 0 10 0 0
    items:
      - type: string
        tooltip: Username for the initial admin user
        required: true
        hideLabel: false
        width: 155

      - type: displayfield
        markup: Admin Password
        width: 113
        cls: x-form-item-label
        margins: 0 11 0 0

      - type: string
        inputType: password
        tooltip: Password for the initial admin user
        required: true
        hideLabel: false
        width: 155

  - name: email
    type: string
    caption: Admin Email
    tooltip: Email address for the initial admin user
    required: false
    vtype: email

  - name: workerEnabled
    type: checkbox
    caption: Enable Workers
    tooltip: Enable RQ workers
    value: true
    showIf:
      true:
        - type: compositefield
          caption: High Queue
          defaultMargins: 0 10 0 0
          items:
            - name: highQueue
              type: spinner
              tooltip: Number of workers to run for the high priority queue
              default: 1
              required: true
              editable: true
              min: 1
              width: 100

            - type: displayfield
              markup: Default Queue
              width: 113
              margins: 0 11 0 0

            - name: defaultQueue
              type: spinner
              tooltip: Number of workers to run for the default priority queue
              default: 1
              required: true
              editable: true
              min: 1
              width: 100

            - type: displayfield
              markup: Low Priority Queue
              width: 113
              margins: 0 11 0 0

            - name: lowQueue
              type: spinner
              caption: Low Queue
              tooltip: Number of workers to run for the low priority queue
              default: 1
              required: true
              editable: true
              min: 1
              width: 100

  - name: dbType
    type: list
    caption: Database Type
    tooltip: Deploy PostgreSQL in standalone or cluster mode
    values:
      - value: standalone
        caption: Standalone
      - value: cluster
        caption: Cluster
    default: standalone

  - name: dbDiskLimit
    type: spinner
    caption: Database Disk Size
    tooltip: Size of the database disk in GB
    default: 10
    required: true
    editable: true
    min: 1

  - name: redisDiskLimit
    type: spinner
    caption: Redis Disk Size
    tooltip: Size of the Redis disk in GB
    default: 10
    required: true
    editable: true
    min: 1

  - name: enableBackup
    type: checkbox
    caption: Enable Backups
    tooltip: Enables database backups
    value: false
    showIf:
      true:
        - name: backupRegion
          type: regionlist
          caption: Backup Region
          tooltip: Choose a region for database backups, preferably in a different availability zone
          required: true
          disableInactive: true
          hidden: false
          selectFirstAvailable: true

        - name: backupType
          type: list
          caption: Backup Storage Type
          tooltip: Storage type for database backups
          values:
            - value: 1
              caption: Standalone Storage
            - value: 2
              caption: Cluster Storage
          default: 1
          showIf:
            2:
              - name: backupNodesCount
                type: spinner
                caption: Nodes Count
                tooltip: Number of nodes in the backup cluster
                default: 3
                min: 3
                max: 7

        - name: backupDiskLimit
          type: spinner
          caption: Backup Disk Size
          tooltip: Size of the backup disk in GB
          default: 100
          required: true
          editable: true
          min: 5

        - name: backupSchedule
          type: list
          caption: Backup Schedule
          tooltip: Schedule for database backups
          values:
            - value: 0 * * * *
              caption: "Hourly (at minute 0)"
            - value: 0 0 * * *
              caption: "Daily (at 00:00)"
            - value: 0 0 * * 0
              caption: "Weekly (at 00:00 on Sunday)"
            - value: 0 0 1 * *
              caption: "Monthly (at 00:00 on day 1)"
          default: 0 0 * * *

        - name: backupCount
          type: spinner
          caption: Number of backups
          tooltip: "The number of newest backups to be kept during rotation."
          min: 1
          max: 30
          default: 5
