fields:
  - name: deploymentType
    type: list
    caption: Deployment Type
    tooltip: Development is for a single node setup and production are for multi-node setups
    values:
      - value: development
        caption: Development
      - value: production
        caption: Production
    default: development

  - name: version
    type: list
    caption: NetBox Version
    tooltip: Version of NetBox to install
    values:
      - value: v3.4-2.5.3
        caption: v3.4
    default: v3.4-2.5.3

  - name: loglevel
    type: list
    caption: Log Level
    tooltip: Log level for NetBox
    values:
      - value: DEBUG
        caption: DEBUG
      - value: INFO
        caption: INFO
      - value: WARNING
        caption: WARNING
      - value: ERROR
        caption: ERROR
      - value: CRITICAL
        caption: CRITICAL
    default: INFO

  - name: enableWorkers
    type: checkbox
    caption: Enable Workers
    tooltip: Enable RQ workers
    value: true
    showIf:
      true:
        - name: highQueue
          type: spinner
          caption: High Priority Queue
          tooltip: Number of workers to run for the high priority queue
          default: 1
          required: true
          editable: true
          min: 1

        - name: defaultQueue
          type: spinner
          caption: Default Priority Queue
          tooltip: Number of workers to run for the default priority queue
          default: 1
          required: true
          editable: true
          min: 1

        - name: lowQueue
          type: spinner
          caption: Low Priority Queue
          tooltip: Number of workers to run for the low priority queue
          default: 1
          required: true
          editable: true
          min: 1

  - name: dbDiskLimit
    type: spinner
    caption: Database Disk Size
    tooltip: Size of the database disk in GB
    default: 10
    required: true
    editable: true
    min: 1

  - name: redisDiskLimit
    type: spinner
    caption: Redis Disk Size
    tooltip: Size of the Redis disk in GB
    default: 10
    required: true
    editable: true
    min: 1
