fields:
  - name: deploymentType
    type: list
    caption: Deployment Type
    tooltip: Development is for a single node setup and production are for multi-node setups
    values:
      - value: development
        caption: Development
      - value: production
        caption: Production
    default: development
    showIf:
      production:
        - name: loadGrowth
          type: list
          caption: Scaling Strategy
          tooltip: |
            Configure auto-scaling triggers, i.e. how fast the system responds to load spikes by adding or removing nodes.
            <p>Read more about <a href="https://docs.jelastic.com/automatic-horizontal-scaling">Automatic Horizontal Scaling</a></p>
          values:
            - value: slow
              caption: Low Load
              tooltip: <h2>Low load scaling strategy</h2>add 1 new node when CPU > 70% <p>remove when CPU < 20%</p>
            - value: medium
              caption: Medium Load
              tooltip: <h3>Medium load scaling strategy</h3>add 1 new node when CPU > 50% <p>remove when CPU < 20%</p>
            - value: fast
              caption: High Load
              tooltip: <h3>High load scaling strategy</h3>add 2 new nodes when CPU > 30% <p>remove when CPU < 10%</p>
          default: slow

  - name: version
    type: list
    caption: NetBox Version
    tooltip: Version of NetBox to install
    values:
      - value: v4.2
        caption: v4.2
      - value: v4.1
        caption: v4.1
      - value: v4.0
        caption: v4.0
      - value: v3.7
        caption: v3.7
      - value: v3.6
        caption: v3.6
      - value: v3.5
        caption: v3.5
      - value: v3.4
        caption: v3.4
    default: v4.2

  - name: loglevel
    type: list
    caption: Log Level
    tooltip: Log level for NetBox
    values:
      - value: DEBUG
        caption: DEBUG
      - value: INFO
        caption: INFO
      - value: WARNING
        caption: WARNING
      - value: ERROR
        caption: ERROR
      - value: CRITICAL
        caption: CRITICAL
    default: INFO

  - name: highQueue
    type: spinner
    caption: High Priority Queue
    tooltip: Number of workers to run for the high priority queue
    default: 0
    editable: true
    min: 0

  - name: defaultQueue
    type: spinner
    caption: Default Priority Queue
    tooltip: Number of workers to run for the default priority queue
    default: 1
    required: true
    editable: true
    min: 1

  - name: lowQueue
    type: spinner
    caption: Low Priority Queue
    tooltip: Number of workers to run for the low priority queue
    default: 0
    editable: true
    min: 0

  - name: dbDiskLimit
    type: spinner
    caption: Database Disk Size
    tooltip: Size of the database disk in GB
    default: 10
    required: true
    editable: true
    min: 1

  - name: redisDiskLimit
    type: spinner
    caption: Redis Disk Size
    tooltip: Size of the Redis disk in GB
    default: 10
    required: true
    editable: true
    min: 1
