fields:
  - name: version
    type: list
    caption: NetBox Version
    tooltip: Version of NetBox to install
    values:
      - value: v3.3
        caption: v3.3
      - value: v3.4
        caption: v3.4
    default: v3.4

  - name: username
    type: string
    caption: Admin Username
    tooltip: Username for the initial admin user
    required: true

  - name: password
    type: string
    inputType: password
    caption: Admin Password
    tooltip: Password for the initial admin user
    required: true

  - name: email
    type: string
    caption: Admin Email
    tooltip: Email address for the initial admin user
    required: false
    vtype: email

  - name: workers
    type: toggle
    caption: Enable Workers
    tooltip: Enable RQ workers
    value: false
    showIf:
      true:
        - name: workerCount
          type: number
          caption: Worker Count
          min: 1
          default: 1
          required: true
          tooltip: Number of rq workers to run
