fields:
  - name: version
    type: list
    caption: Version
    tooltip: Version of plugin to install
    values:
      - value: v0.4.0
        caption: v0.4.0
    default: v0.4.0

  - name: restartContainer
    type: checkbox
    caption: Restart NetBox container
    tooltip: Restart NetBox container after install/uninstall
    default: true
    required: false
