name: JPS Manifest

on:
  push:
    branches:
      - master

jobs:
  update-manifest:
    runs-on: ubuntu-22.04-sh

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Python Dependencies
      run: pip install requests yaml

    - name: Run Update Script
      env:
        JELASTIC_TOKEN: ${{ secrets.JELASTIC_TOKEN }}
      run: python .github/jca.py
