name: PR Check

on:
  pull_request:
    branches: [ master ]

jobs:
  check-manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find manifest.jps files
      id: find-manifest
      run: |
        files=$(find . -name 'manifest.jps')
        echo "::set-output name=files::$files"

    - name: Validate baseUrl in manifest files
      run: |
        repo_owner="${{ github.repository_owner }}"
        repo_name=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        expected_base_url="https://raw.githubusercontent.com/${repo_owner}/${repo_name}/master"

        for file in ${{ steps.find-manifest.outputs.files }}
        do
          baseUrl=$(yq eval '.baseUrl' $file)
          if [[ "$baseUrl" != "$expected_base_url" ]]; then
            echo "Invalid baseUrl format in $file. Expected ${expected_base_url}, but found ${baseUrl}"
            exit 1
          fi
        done
