name: Update Plugin Versions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  update-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Python Dependencies
        run: pip install requests

      - name: Run Update Script
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: python .github/plugins.py

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Plugin Versions
          branch: master
          file_pattern: 'addons/*/config/versions.yaml'
          commit_author: Author <actions@github.com>
